/*
 Copyright (C) 2014 Suriyan Ramasami <suriyan.r@gmail.com>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "Help.hpp"

#include "Compatibility.hpp"

// Help text
const char help[]=
"\n"
"\n"
"                                           M . a . s . a . l . a . M . a . t . e\n"
"\n"
"\n"
"Introduction:\n"
"   MasalaMate is an IRC client that is specifically tailored towards the " CHANNEL_MAIN " channel on IRC.\n"
"\n"
"   The following sections will guide you through the steps necessary to unleash the full power of \"MasalaMate\".\n"
"\n"
"   When you run MasalaMate, it automatically connects to the IRC Server and joins channels " CHANNEL_MAIN " and " CHANNEL_CHAT ". " CHANNEL_MAIN " (refered to as the main channel henceforth) is the channel where users exchange files. " CHANNEL_CHAT " (referred to as the chat channel henceforth) is the channel where you can hang out and chat with friends and ask for or provide help.\n"
"\n"
"   Note: To check for and download new versions of MasalaMate, please visit groups.yahoo.com/group/masalamate.\n"
"\n"
"TABS in the User Interface:\n"
"\n"
"   The following tabs are displayed at the bottom of the screen - from left to right:\n"
"1. \"IRCsuper Network\" =>\n"
"    This tab displays miscellaneous information pertinent to the IRC Server.\n"
"    It also displays the responses of MasalaMate to user actions like Downloads etc.\n"
"2. \"" CHANNEL_MAIN "\" =>\n"
"    This tab displays the messages or advertisements sent by users in the main channel.\n"
"3. \"" CHANNEL_CHAT "\" =>\n"
"    This tab displays the goings on in the chat channel where you can chat with other users.\n"
"4. \"Messages\" =>\n"
"    This tab lets you access private messages you receive from other users.\n"
"    To Chat with a specific user, highlight the nick on the right.\n"
"    Double clicking on a nick in the " CHANNEL_MAIN " or " CHANNEL_CHAT " channel, will immediately take you to this tab, positioned to private chat with that nick.\n"
"5. \"File Search\" =>\n"
"    This tab lets you search for the files you would like to download. You will find three buttons titled: \"Search File\", \"List Nick\", \"List All\". You will also find three tickable elements titled: \"Open Sends\", \"Open Queues\", \"Non Firewalled\".\n"
"    \"Open Sends\", \"Open Queues\" and \"Non Firewalled\" allow one to change the behavior of a search. If \"Open Sends\" is ticked, then the search returns a list which has open sends. If \"Open Queues\" is ticked, then the search returns a list which has open queues. If both are ticked, then the search returns a list which has open sends or open queues or both. If both are unticked, then the search returns a list even if it doesnt have an open send or queue slot. If \"Non Firewalled\" is ticked, then additionally only the servers which are not firewalled (or whose firewall state we dont know) are listed.\n"
"    The \"Search File\", \"List Nick\" and \"List All\" buttons let you search according to a given critera.\n"
"    Entering a text, for example \"Maja\" and clicking on \"Search File\" will list filenames which have \"Maja\" in them, like: \"MoujAurMajaMasti.avi\".\n"
"    Entering a text, for example \"alphakaya\" and clicking on \"Search Nick\" will list the files served by the nick \"alphakaya\". Note that the nick names have to match exactly.\n"
"    Clicking on \"List All\" lists all the files which we know are being served at the current time. This list will be fairly accurate, but not guaranteed to be accurate.\n"
"    Clicking on the Label Headers will sort the List.\n"
"    Highlighting a file and Right Clicking will bring up a PopUp menu. Choosing \"Download Selected Line\", will try to download that file. One should note that MasalaMate gets file information automatically by accessing triggers. Hence the longer it has been on, the more information that it has. Ideally in 20 minutes, you should have an extensive list. One should also note, that if your incoming port 8124 is blocked, your success will be considerably low.\n"
"6. \"Waiting\" =>\n"
"    This tab displays a list of files that you requested but have been placed in queues by the servers. This listing should be used as a guideline, as its not very reliable.\n"
"    Selecting a file, and Right clicking will bring up a PopUp menu, which will work on that Selected Line.\n"
"7. \"Downloads\" =>\n"
"    This tab shows a list of files that you are currently downloading. Selecting a File and right clicking will bring up a PopUp Menu, which will work on the selected line.\n"
"    Completed downloads will appear in this tab and will be marked COMPLETE. Downloads which were stopped partially, for whatever reason will be marked PARTIAL. You can multiple lines in this tab, and remove them from the list, by double lcicking. To get rid of all the lines marked as COMPLETE or PARTIAL, you can click on the \"Clear Screen\" button.\n"
"8. \"File Server\" =>\n"
"    This tab displays the nicks of people who are currently downloading from you. You can force send a file to a nick, by right clicking and selecting \"Send Selected Queue\" on the line which shows the nick being in QUEUE.\n"
"\n"
"\n"
"MasalaMate Menu:\n"
"1. \"File\" =>\n"
"    Connection =>\n"
"    Used to change the Connection Type. Most of the users need not use this. This is for people behind a proxy/BNC/socks 4/socks5\n"
"\n"
"    ReConnect IRC =>\n"
"    Used to disconnect from the Network and Reconnect again.\n"
"\n"
"    Quit =>\n"
"    Clicking on the Quit button will shutdown MasalaMate\n"
"\n\n"
"2. \"Nick\" =>\n"
"    Set NickName =>\n"
"    Used to change your nick. You can also change by typing: /nick <new nick>\n"
"    where, <new nick> is the new nick you want to take up.\n"
"    Example: /nick sundaresan\n"
"    Set NickPass =>\n"
"    If you have registered the above set Nick, you can enter the password here. This will automatically identify your nick.\n"
"\n\n"
"3. \"Dir\" =>\n"
"    Partial Dir =>\n"
"     The Partial submenu allows you to access the folder where the partially downloaded files are stored on your hard disk. These files might either be in the process of being downloaded or may have been downloaded partially and then stopped\n"
"\n"     
"    Serving Dir =>\n"
"     The Serving submenu allows you to access the folder where the fully downloaded files are stored in your hard disk.\n"
"\n"
"    Set Partial Dir =>\n"
"     This submenu allows you to set the Partially Downloading Folder.\n"
"\n"
"    Set Serving Dir =>\n"
"     This submenu allows you to set the Serving Folder.\n"
"\n"
"    Update Server =>\n"
"     If you have made changes (removed or added files) in the Serving Folder, you can select this to instruct MasalaMate to reread the Serving Folder, so it internally has a list of files which are in sync with what are physically present.\n"
"\n\n"
"4. \"Font\" =>\n"
"    Change Font =>\n"
"    The Change Font submenu allows you to select your own Fonts for the display.\n"
"\n\n"
"5. \"Tools\" =>\n"
"    Rollback Truncate File =>\n"
"    This should be used if there are problems Resuming files. It will allow you to truncate a file in your Partial Folder, so that it can successfully resume, if the file is corrupted towards the end. This kind of problems ususally happen cause of a power outage or a MasalaMate crash. This command should be used together with the \"Chcek File Integrity\" Option available in the right click popup menu available in the \"File Search\" TAB\n"
"\n\n"
" Commands:\n"
"   The folowing commands are supported in MasalaMate:\n"
"   a) /portcheckme <nick>\n"
"      Example: /portcheckme Gurudev\n"
"      This command will work only if <nick> (Gurudev, in our example) is also using MasalaMate.\n"
"      It requests the nick, Gurudev, to check if your incoming port 8124 is open. You will receive a response from <nick> (Gurudev in our example) in your Messages TAB\n"
"\n"
"   b) /portcheck <nick>\n"
"      Example: /portcheck Gurudev\n"
"      This will check if the 8124 port of Gurudev is open. This is for diagnostic purposes alone. Check your Server window for the results.\n"
"\n"
"   c) /dcc send <nick>\n"
"      Example: /dcc send Gurudev\n"
"      After issuing this command, a File Selection dialog will appear. You can select the file you want to send to <nick> (Gurudev in our example)\n"
"\n"
"   d) All /ctcp and /msg commands are supported.\n"
"      All CTCP triggers displayed in #indianmasala can be accessed manually. MasalaMate will automatically get the list of files that are being served by that user.\n"
"\n"
"   e) /me <Message>\n"
"      These are action messages which appear in the channel in a different form. Try it out to see how they look.\n"
"      Example: /me is eating dinner\n"
"\n"
"   f) /upnp <search|addport|delport|getmappings>\n"
"      MasalaMate can identify most UPNP enabled routers, and correctly portforward port 8124 to the machine its running from. Hence if you are behind a router, you should enable its UPNP. These commands are provided to let the user play with the upnp settings.\n"
"\n"
"   g) /clear\n"
"      Clears the window its issued in.\n"
"\n"
"   h) /nick <new_nick>\n"
"      Will attempt to take on new_nick, if possible\n"
"\n"
"   i) /fserv <sends|queues|smallfilesize|print> <overall|each> <value>\n"
"\n"
"   j) /cap <upload|download|print> <each|overallmax|overallmin> <value>\n"
"\n"
"   k) Ctrl K - to add color codes\n"
"      Example: Ctrl K04Red     - will put text in red on the screen\n"
"      Can be used to change background color as: Ctrl Kfg color,bg color\n"
"        Colors follow that of mirc as follows:\n"
"        00 = white    01 = black   02 = blue     03 = green\n"
"        04 = red      05 = brown   06 = purple   07 = orange\n"
"        08 = yellow   09 = lime    10 = teal     11 = cyan\n"
"        12 = royal    13 = pink    14 = grey     15 = silver\n"
"\n\n"
" BUTTONS:\n"
"   The buttons make it easy to use the above listed commands.\n"
"   The description of these buttons from left to right is as follows:\n"
"   a) Single click to the Fonts Menu.\n"
"   b) Clears the current screen.\n"
"   c) Opens a DCC Send dialog with the selected Nick.\n"
"   d) Single click to view your Serving Folder.\n"
"   e) Single click to view your Partial Folder.\n"
"   f) Issues a /portcheck command to the highlighted Nick.\n"
"   g) Issues a /portcheckme command to the highlighted Nick.\n"
"   h) Firewall button: If red you are firewalled. If green you are not firewalled. It initially starts off as red.\n"
"   i) Single Click to get to the Help screen you are reading currently.\n"
"   j) Search Text: You can enter a search text and click on the arrow. It will highlight it if found in the current TAB.\n"
"   k) Green TAB showing 100 %: This is currently valid only in the \"File Search\" TAB, when sorting or listing files. It is used as a progress bar during those times.\n"
"\n\n"
" THE RIGHT CLICK POPUP MENU in the CHANNEL TABs:\n"
"     Right Clicking brings up a PopUp menu, whose actions act on the Nick selected in the channel\n"
"     The PopUp consists of the following items:\n"
"     - Port Check      - Check if the nick highlighted has its port open\n"
"     - Port Check Me   - Request the highlighted nick to check out ports\n"
"     - Update Files    - Update Files served by the highlighted nick\n"
"     - List Files      - List Files that the highlighted nick is serving\n"
"     - WHOIS           - Issue a /whois on the highlighted nick; results appear in the Network Window\n"
"     - CTCP Ping       - ping the highlighted nick; results appear in the Network Window\n"
"     - CTCP Version    - get the version of the client used by the highlighted nickl results appear in the Network Window\n"
"     - DCCAllow Add    - Allow the highlighted nick to send you restricted files; like: exe/rar/zip etc\n"
"     - DCCAllow Del    - DisAllow the highlighted nick from sending you restricted files. Note by default all users are not allowed.\n"
"     - DCC Send        - Send a file to the highlighted nick\n"
"\n\n"
" THE RIGHT CLICK POPUP MENU in the File Search/Waiting/Downloads TABs:\n"
"     Right Clicking brings up a PopUp menu, whose actions act on the Selected Line\n"
"     The Menu items are self explanatory.\n"
"\n\n"
" TIPS:\n"
"   a) Copy/Paste: Pressing the left mouse button and dragging it over a region will automatically Copy the text highlighted. You can paste it by pressing together: Ctrl v\n"
"\n"
"   b) Update List: Selecting a nick, Right click menu -> choose \"Update Files\" will force MasalaMate to attempt the trigger of the selected nick. This will grab the names of the files that <nick> is serving (if <nick> is indeed serving, and we are able to connect to his File Server). Check the Server TAB on the actions that MasalaMate is doing.\n"
"\n"
"   c) List Files: Selecting a nick, Right click menu -> choose \"List Files\" will list the files that are being served by nick in the \"Files Search\" menu. (You can get an empty list if MasalaMate does not have the information).\n"
"\n"
"   d) Clicking on a nick in the scrolling window, will highlight the nick in the Nick list to the right. This is convenient when you want to send a file to the nick, or choose a command from the buttons which need the nick highlighted.\n"

;
